### ISSUE TITLE
Add Detailed Procedure to Readme for How Generating Planner.

### ISSUE THREAD

**Issue by regenerous** [innocenat/supernote-planner#1]
Love what you've done here and it fits what I want perfectly but I'm stuck because I have no idea how to use this repo to get something I can load in my Supernote. I've got some hobby level experience coding (mostly in python) but never done php.  It would be great and add tremendous value to this repo if you could include some sort of procedure for generating the planner using your repo.

**Comment by innocenat** [comment]
You can get prebuilt version from the Release page: https://github.com/innocenat/supernote-planner/releases/tag/v2023.2

For customizing and building from source, you need to install PHP command line, and run `php make-planner.php`.

**Comment by regenerous** [comment]
Thank you! Must've missed that. Will submit a PR to add your comment to ReadMe since I believe it's beneficial.
